# Generated by Django 5.1.3 on 2025-04-07 09:14

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_notice_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='year',
        ),
    ]
